In [2]:
import pandas as pd
import numpy as np

### This file is specifically designed as a practice notebook for exploring different pandas tools

Aggregation

In [52]:
df0 = pd.DataFrame([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [np.nan, np.nan, np.nan]], 
columns= ['A', 'B', 'C'])

In [53]:
df0.head()

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [54]:
df0.agg(['sum', 'min'])  # by default, using aggregate applies on the columns

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [55]:
df0.agg({'A': ['sum', 'min'], 'B': ['min', 'max']})

        A    B
sum  12.0  NaN
min   1.0  2.0
max   NaN  8.0

In [56]:
df0.agg("mean", axis = 1)  # rowwise aggregation

0    2.0
1    5.0
2    8.0
3    NaN
dtype: float64

In [57]:
df0.agg(x=('A', 'max'), y=('B', 'min'), z=('C', 'mean'))

     A    B    C
x  7.0  NaN  NaN
y  NaN  2.0  NaN
z  NaN  NaN  6.0

In [58]:
df0

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [59]:
df0.sum()
df0.count()
df0.median()
df0.quantile([0.25, 0.75])
df0.apply(lambda x: x **2)
df0.min()
df0.max()
df0.mean()
df0.var()
df0.std()

A    3.0
B    3.0
C    3.0
dtype: float64

In [66]:
df0['ranked_densed'] = df0['A'].rank(method = 'dense')
df0['rank_min'] = df0['C'].rank(method='min')

In [67]:
df0

     A    B    C  ranked_densed  rank_min
0  1.0  2.0  3.0            1.0       1.0
1  4.0  5.0  6.0            2.0       2.0
2  7.0  8.0  9.0            3.0       3.0
3  NaN  NaN  NaN            NaN       NaN