In [2]:
import pandas as pd

In [3]:
bios = pd.read_csv("./data/bios.csv")

In [4]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

What should we clean up at first?

- [x] Get rid of bullet points in the names
- [] Get rid of extra columns
- [] Try to ensure that there is only one piece of information in every column, for example, we should separate the birthday/location in the `Born` and `Die` Column
- [] Parse out city, region, and country from `Born` column
- [] Parse out dates form `Born` & `Die` column

In [6]:
df = bios.copy()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

Get rid of bullet points in the dataframe

In [8]:
df['name'] = df['Used name'].str.replace('•', " ")

In [10]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

In [39]:
# We want to split the measurements into two separete columns
df[['height_cm', 'weight_kg']] = df['Measurements'].str.split('/', expand = True)

In [40]:
# Check to make sure all the values in Measurements have the '/' symbol in it
df[~df['Measurements'].str.contains('/', na=False) & df['Measurements'].notna()]
# Above will return all the measurements that does not contain /

# Get rid of "cm" and the "kg" from our new columns

# df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178 cm,None
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191 cm,None
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,120 kg,None
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161 cm,None
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161 cm,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov,168 cm,None
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva,160 cm,None
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina,190 cm,None
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183 cm,None
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166 cm,None

In [57]:
# some small toy example to infer the overall behaviour on the actual data frame.
small_data = pd.DataFrame(['183 cm', '190cm / 150 kg', '100 kg'], columns = ['Measurements'])
small_data[['height_cm', 'weight_kg']] = small_data['Measurements'].str.split('/', expand = True)

# Strategy, we first populate hte weight_kg column with the values of the height_cm after splitting, this ensures that if weight_kg is NAN, it gets the value of either the height or the actual weight
small_data.fillna({'weight_kg': small_data['height_cm']}, inplace=True)

# Then we strip the unit away
small_data['height_cm'] = pd.to_numeric(small_data['height_cm'].str.strip(' cm'), errors="coerce")
small_data['weight_kg'] = pd.to_numeric(small_data['weight_kg'].str.strip(' kg'), errors="coerce")

small_data.head()

     Measurements  height_cm  weight_kg
0          183 cm      183.0        NaN
1  190cm / 150 kg      190.0      150.0
2          100 kg        NaN      100.0

In [42]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [58]:
# df['height_cm'] = df['height_cm'].str.extract(r'(\d+)')

# However, we do not want to use this approach, when we observe from the toy example we see above. We see that for 
# weights of 100kg, after splitting, it will also fall under the heights column. So to effectively avoid that situation, 
# we should leverage split instead.
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,height_cm
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,height_cm

In [ ]:
# After expriementing with the toy dataset, we can apply the same strategy on the column of measurements

# Since we have already divided into height_cm and weight_kg, we now just need to perform copy and unit removals
df.fillna({"weight_kg": df['height_cm']}, inplace=True)
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,height_cm
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,height_cm

In [63]:
df[~df["weight_kg"].notna()]  # Wec check and see that all values of weight_kg have been filled with real values

Empty DataFrame
Columns: [Roles, Sex, Full name, Used name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, name, height_cm, weight_kg]
Index: []

In [64]:
df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(" cm"), errors="coerce")
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(" kg"), errors="coerce")

In [65]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN

In [ ]:
# Parse out dates from Born and Die columns
date_pattern = r'(\d+ \w+ \d{4})'

df['Born Date'] = df['Born'].str.extract(date_pattern)

In [69]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,Born Date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,12 December 1886
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1 April 1969
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,13 August 1898
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,11 May 1895
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,17 April 1878

In [84]:
# Build small examples
small_data = pd.DataFrame(['1895 in Scotland', '12 December 1990 in Boston'], columns=['Born'])
dat_pattern = r'(\d+ \w+ \d{4}|\d{4})'
small_data['born_date'] = small_data['Born'].str.extract(date_pattern)

In [82]:
small_data

                         Born         born_date
0            1895 in Scotland              1895
1  12 December 1990 in Boston  12 December 1990

In [85]:
date_pattern = r'(\d+ \w+ \d{4}|\d{4})'
df['born_date'] = df['Born'].str.extract(date_pattern)
df['born_date'] = pd.to_datetime(df['born_date'], format="mixed", errors='coerce')

In [88]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,Born Date,born_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,12 December 1886,1886-12-12
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1 April 1969,1969-04-01
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,13 August 1898,1898-08-13
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,11 May 1895,1895-05-11
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,17 April 1878,1878-04-17

In [100]:
# Get city, region, and country from Born column
location_pattern = r'in ([\w\s]+), ([\w\s]+) \((\w+)\)'

In [101]:
df['Born'].str.extract(location_pattern)

                   0                1    2
0           Bordeaux          Gironde  FRA
1             Meulan         Yvelines  FRA
2                NaN              NaN  NaN
3        Paris VIIIe            Paris  FRA
4         Wandsworth          England  GBR
...              ...              ...  ...
145495         Serov       Sverdlovsk  RUS
145496           NaN              NaN  NaN
145497        Kotlas      Arkhangelsk  RUS
145498           NaN              NaN  NaN
145499  Dulwich Hill  New South Wales  AUS

[145500 rows x 3 columns]

In [103]:
df[['born_city', 'born_region', 'born_country']] = df['Born'].str.extract(location_pattern, expand = True)

In [117]:
df['died_date'] = df['Died'].str.extract(date_pattern)
df['died_date'] = pd.to_datetime(df['died_date'], errors = "coerce")

In [119]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
 16  name           145500 non-null  object
 17  height_cm      106651 non-null  float64
 18  weight_kg      102070 non-null  float64
 19  Born Date      141690 non-null  object
 20  born_date      143693 non-null  datetime64[ns]
 21  born_city      90740 non-null   object
 22  born_region    90740 non-null   object
 23  born_country   90740 non-null   object
 24  died_date      31928 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(20)
memory usage: 27.8+ MB

In [120]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
df.value_counts('born_country', ascending=False).head(10)

born_country
USA    9628
GBR    5645
CAN    4456
ITA    4166
GER    3700
RUS    3120
AUS    3006
ESP    2578
SWE    2568
FRA    2546
Name: count, dtype: int64

In [121]:
# Remove any unnecessary columns
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'height_cm', 'weight_kg', 'Born Date', 'born_date', 'born_city',
       'born_region', 'born_country', 'died_date'],
      dtype='object')

In [122]:
columns_to_keep = ['athlete_id', 'name', 'born_date', 'born_city', 'born_region', 'born_country', 
                   'NOC', 'height_cm', 'weight_kg', 'died_date']
df_clean = df[columns_to_keep]

In [123]:
df_clean.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,1898-08-13,NaN,NaN,NaN,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [125]:
df_clean.to_csv('./clean-data/bios.csv', index=False)

### Clean the Results

In [127]:
results = pd.read_csv('./results/results.csv')

C:\Users\mosbi\AppData\Local\Temp\ipykernel_19120\2306265425.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv('./results/results.csv')

In [129]:
results.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [132]:
results['place'] = results['Pos'].str.extract(r'(\d+)')
results.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,place
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,17
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,32
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,8
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,4

In [134]:
results.drop(columns=["Unnamed: 7"], inplace=True)

In [135]:
results.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,place
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,17
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,32
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,8
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,4